name: Publish Packages

on:
  push:
    tags:
      - 'v*'   # publica cuando hagas un tag tipo v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          standalone: false

      - name: Setup Node
        run: pnpm env use -g 23.10.0
        timeout-minutes: 1

      - name: Install depends
        run: pnpm install


      - name: Build packages
        run: pnpm run build
        # -r = recursive, corre build en cada workspace

      - name: Publish packages
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
